#!/usr/bin/env python3
"""Write OVH credentials to .env in the current working directory."""

import argparse
import os
import sys
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Write OVH credentials to .env")
    parser.add_argument("--app-key", required=True, help="OVH Application Key")
    parser.add_argument("--app-secret", required=True, help="OVH Application Secret")
    parser.add_argument("--consumer-key", required=True, help="OVH Consumer Key")
    parser.add_argument("--endpoint", required=True, help="Endpoint: eu, ca, or us")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env")
    args = parser.parse_args()

    env_path = Path.cwd() / ".env"

    if env_path.exists() and not args.force:
        print(f"ERROR: {env_path} already exists.", file=sys.stderr)
        print("Use --force to overwrite, or edit the file manually.", file=sys.stderr)
        return 1

    endpoint_map = {"eu": "ovh-eu", "ca": "ovh-ca", "us": "ovh-us"}
    endpoint = endpoint_map.get(args.endpoint.lower(), args.endpoint)

    content = f"""\
# OVH API Credentials — generated by scripts/write_env.py
# Do NOT commit this file to version control.
OVH_APPLICATION_KEY={args.app_key}
OVH_APPLICATION_SECRET={args.app_secret}
OVH_CONSUMER_KEY={args.consumer_key}
OVH_ENDPOINT={endpoint}
"""

    env_path.write_text(content)

    # Restrict to owner read/write only (600) — credentials should not be world-readable
    env_path.chmod(0o600)

    print(f"Credentials written to: {env_path.resolve()}")
    print(f"File permissions set to 600 (owner read/write only)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
